<a href="https://colab.research.google.com/github/zarczynsky/ships/blob/main/ships.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic ship game

In [ ]:
import random 
import numpy as np

In [ ]:
class UserTable:
  def __init__(self, size_of_table_x, size_of_table_y):
    self.table = np.zeros([size_of_table_x, size_of_table_y])

  def change_element(self, x: int, y:int, down: bool):
    if down:
      self.table[x, y]=1
    else:
      self.table[x, y]=-1

In [ ]:
class Table:
  def __init__(self, size_of_table_x, size_of_table_y, number_of_ships=5):
    self._table = np.zeros([size_of_table_x, size_of_table_y])
    for i in range(0,number_of_ships):
      x=random.randint(0,size_of_table_x-1)
      y=random.randint(0,size_of_table_y-1)
      self._table[x,y]=1

    self.user_table=UserTable(size_of_table_x=size_of_table_x, size_of_table_y=size_of_table_y)

  def check(self,x,y) -> bool:
    try:
      if self._table[x, y]==1:
        self.user_table.change_element(x, y, True)
        if len(self._table[self._table==1])==len(self.user_table[self.user_table==1]):
          return True
      else:
        self.user_table.change_element(x, y, False)

      return False
    except Exception as error:
      print('You did something wrong!!!\n' + str(error))


In [ ]:
t = Table(6,6)

In [ ]:
game = False
table = Table(6, 6, 1)
print('This is Adaś game. To turn it off just write -1 in x or y.')
while game != True:
  try:
    x = int(input('X: '))
    y = int(input('Y: '))
  except Exception as error:
      print('You did something wrong!!!\n' + str(error))
  if x == -1 or y == -1:
    break
  game = table.check(x, y)
  print(table.user_table.table)


This is Adaś game. To turn it off just write -1 in x or y.
X: the
You did something wrong!!!
invalid literal for int() with base 10: 'the'
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
X: -2
Y: -3
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
X: -2
Y: 8
You did something wrong!!!
index 8 is out of bounds for axis 1 with size 6
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
X: -9
Y: -4
You did something wrong!!!
index -9 is out of bounds for axis 0 with size 6
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


KeyboardInterrupt: ignored